nelmio_api_doc:
    documentation:
        info:
            title: Commande API
            description: Commande API
            version: 1.0.0
        security:
            -   Bearer: [ ]

    areas:
        path_patterns:
            - ^/api
